# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/Users/tonyt/Desktop/CS411/EC/SuRF

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/Users/tonyt/Desktop/CS411/EC/SuRF

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/tonyt/Desktop/CS411/EC/SuRF/CMakeFiles /mnt/c/Users/tonyt/Desktop/CS411/EC/SuRF/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/tonyt/Desktop/CS411/EC/SuRF/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test_surf_small

# Build rule for target.
test_surf_small: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_surf_small
.PHONY : test_surf_small

# fast build rule for target.
test_surf_small/fast:
	$(MAKE) -f test/unitTest/CMakeFiles/test_surf_small.dir/build.make test/unitTest/CMakeFiles/test_surf_small.dir/build
.PHONY : test_surf_small/fast

#=============================================================================
# Target rules for targets named test_surf_builder

# Build rule for target.
test_surf_builder: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_surf_builder
.PHONY : test_surf_builder

# fast build rule for target.
test_surf_builder/fast:
	$(MAKE) -f test/unitTest/CMakeFiles/test_surf_builder.dir/build.make test/unitTest/CMakeFiles/test_surf_builder.dir/build
.PHONY : test_surf_builder/fast

#=============================================================================
# Target rules for targets named test_surf

# Build rule for target.
test_surf: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_surf
.PHONY : test_surf

# fast build rule for target.
test_surf/fast:
	$(MAKE) -f test/unitTest/CMakeFiles/test_surf.dir/build.make test/unitTest/CMakeFiles/test_surf.dir/build
.PHONY : test_surf/fast

#=============================================================================
# Target rules for targets named test_suffix

# Build rule for target.
test_suffix: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_suffix
.PHONY : test_suffix

# fast build rule for target.
test_suffix/fast:
	$(MAKE) -f test/unitTest/CMakeFiles/test_suffix.dir/build.make test/unitTest/CMakeFiles/test_suffix.dir/build
.PHONY : test_suffix/fast

#=============================================================================
# Target rules for targets named test_select

# Build rule for target.
test_select: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_select
.PHONY : test_select

# fast build rule for target.
test_select/fast:
	$(MAKE) -f test/unitTest/CMakeFiles/test_select.dir/build.make test/unitTest/CMakeFiles/test_select.dir/build
.PHONY : test_select/fast

#=============================================================================
# Target rules for targets named test_rank

# Build rule for target.
test_rank: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_rank
.PHONY : test_rank

# fast build rule for target.
test_rank/fast:
	$(MAKE) -f test/unitTest/CMakeFiles/test_rank.dir/build.make test/unitTest/CMakeFiles/test_rank.dir/build
.PHONY : test_rank/fast

#=============================================================================
# Target rules for targets named test_label_vector

# Build rule for target.
test_label_vector: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_label_vector
.PHONY : test_label_vector

# fast build rule for target.
test_label_vector/fast:
	$(MAKE) -f test/unitTest/CMakeFiles/test_label_vector.dir/build.make test/unitTest/CMakeFiles/test_label_vector.dir/build
.PHONY : test_label_vector/fast

#=============================================================================
# Target rules for targets named test_louds_dense

# Build rule for target.
test_louds_dense: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_louds_dense
.PHONY : test_louds_dense

# fast build rule for target.
test_louds_dense/fast:
	$(MAKE) -f test/unitTest/CMakeFiles/test_louds_dense.dir/build.make test/unitTest/CMakeFiles/test_louds_dense.dir/build
.PHONY : test_louds_dense/fast

#=============================================================================
# Target rules for targets named test_louds_sparse

# Build rule for target.
test_louds_sparse: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_louds_sparse
.PHONY : test_louds_sparse

# fast build rule for target.
test_louds_sparse/fast:
	$(MAKE) -f test/unitTest/CMakeFiles/test_louds_sparse.dir/build.make test/unitTest/CMakeFiles/test_louds_sparse.dir/build
.PHONY : test_louds_sparse/fast

#=============================================================================
# Target rules for targets named test_louds_dense_small

# Build rule for target.
test_louds_dense_small: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_louds_dense_small
.PHONY : test_louds_dense_small

# fast build rule for target.
test_louds_dense_small/fast:
	$(MAKE) -f test/unitTest/CMakeFiles/test_louds_dense_small.dir/build.make test/unitTest/CMakeFiles/test_louds_dense_small.dir/build
.PHONY : test_louds_dense_small/fast

#=============================================================================
# Target rules for targets named test_bitvector

# Build rule for target.
test_bitvector: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_bitvector
.PHONY : test_bitvector

# fast build rule for target.
test_bitvector/fast:
	$(MAKE) -f test/unitTest/CMakeFiles/test_bitvector.dir/build.make test/unitTest/CMakeFiles/test_bitvector.dir/build
.PHONY : test_bitvector/fast

#=============================================================================
# Target rules for targets named test_louds_sparse_small

# Build rule for target.
test_louds_sparse_small: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 test_louds_sparse_small
.PHONY : test_louds_sparse_small

# fast build rule for target.
test_louds_sparse_small/fast:
	$(MAKE) -f test/unitTest/CMakeFiles/test_louds_sparse_small.dir/build.make test/unitTest/CMakeFiles/test_louds_sparse_small.dir/build
.PHONY : test_louds_sparse_small/fast

#=============================================================================
# Target rules for targets named workload

# Build rule for target.
workload: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 workload
.PHONY : workload

# fast build rule for target.
workload/fast:
	$(MAKE) -f bench/CMakeFiles/workload.dir/build.make bench/CMakeFiles/workload.dir/build
.PHONY : workload/fast

#=============================================================================
# Target rules for targets named workload_multi_thread

# Build rule for target.
workload_multi_thread: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 workload_multi_thread
.PHONY : workload_multi_thread

# fast build rule for target.
workload_multi_thread/fast:
	$(MAKE) -f bench/CMakeFiles/workload_multi_thread.dir/build.make bench/CMakeFiles/workload_multi_thread.dir/build
.PHONY : workload_multi_thread/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... edit_cache"
	@echo "... test_surf_small"
	@echo "... test_surf_builder"
	@echo "... test_surf"
	@echo "... test_suffix"
	@echo "... test_select"
	@echo "... test_rank"
	@echo "... test_label_vector"
	@echo "... test_louds_dense"
	@echo "... test_louds_sparse"
	@echo "... test_louds_dense_small"
	@echo "... test_bitvector"
	@echo "... test_louds_sparse_small"
	@echo "... workload"
	@echo "... workload_multi_thread"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

